In [1]:
from sklearnex import patch_sklearn
patch_sklearn()

Intel(R) Extension for Scikit-learn* enabled (https://github.com/intel/scikit-learn-intelex)


In [2]:
import pandas as pd
import numpy as np

# Simple Notation for Mathmatics in Python
## Linear Algebra
### Vector

In [4]:
# represent vector and use them as our examples
u = np.array([2, 5])
v = np.array([3, 1])

In [5]:
# norm: the measure of the length of one vector
import numpy.linalg as LA
LA.norm(u)

5.385164807134504

In [8]:
# addition
u + v

array([5, 6])

In [7]:
# multiplication by a scalar
1.5 * u

array([3. , 7.5])

In [9]:
# calculate the normalized vector (a vector with unit length)
v / LA.norm(v)

array([0.9486833 , 0.31622777])

In [10]:
# dot product
np.dot(u, v)

11

In [12]:
# calculating the angle between vectors (by using the low of cosine)
def vector_angle(u, v):
    # return radian
    cos_theta = u.dot(v) / LA.norm(u) / LA.norm(v)
    return np.arccos(np.clip(cos_theta, -1, 1))

theta = vector_angle(u, v)
print("Angle =", theta, "radians")
print("      =", theta * 180 / np.pi, "degrees")

Angle = 0.8685393952858895 radians
      = 49.76364169072618 degrees


In [14]:
# projecting 
u_normalized = u / LA.norm(u)
proj = v.dot(u_normalized) * u_normalized
proj

array([0.75862069, 1.89655172])

### Metrics

In [21]:
# represent metrics
A = np.array([
    [10,20,30],
    [40,50,60]
])
B = np.array([[1,2,3], [4,5,6]])

In [16]:
# shape
A.shape, A.size

((2, 3), 6)

In [18]:
# Element Indexing
A[1, 2] # 2nd row, 3rd, column
A[1, :] # 2nd, row vector (as a 1D array)
# see python indexing methods

array([40, 50, 60])

In [19]:
# construct special matrics
np.diag([4, 5, 6]) # construct a diagonal matrix
np.eye(3) # create a 3 * 3 identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [22]:
# Addition
A + B

array([[11, 22, 33],
       [44, 55, 66]])

In [23]:
# Scalar Multiplication
2 * A

array([[ 20,  40,  60],
       [ 80, 100, 120]])

In [26]:
# matrics multiplication
# way 1: by using dot product
D = np.array([
    [2, 3, 5, 7],
    [11, 13, 17, 19],
    [23, 29, 31, 37]
])
E = A.dot(D)
E

array([[ 930, 1160, 1320, 1560],
       [2010, 2510, 2910, 3450]])

In [27]:
# way 2: by @ operater
A @ D 

array([[ 930, 1160, 1320, 1560],
       [2010, 2510, 2910, 3450]])

In [28]:
# matrix transpose
A.T

array([[10, 40],
       [20, 50],
       [30, 60]])

In [29]:
(A @ D).T

array([[ 930, 2010],
       [1160, 2510],
       [1320, 2910],
       [1560, 3450]])

In [30]:
(D.T @ A.T)

array([[ 930, 2010],
       [1160, 2510],
       [1320, 2910],
       [1560, 3450]])

In [39]:
# Matrix Inverse
F = np.array([
        [1, 1.5],
        [0, 1]
    ])
F_inv = LA.inv(F)
F_inv

array([[ 1. , -1.5],
       [ 0. ,  1. ]])

In [41]:
# Determinant
M = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 0]
])
LA.det(M)

27.0

In [42]:
# Eigenvalue & Eigenvectors, trace... can be put on later

# Linear Model

## Solve Linear Model by Normal Equation

In [44]:
# linear-looking data 
X = 2 * np.random.rand(100, 1)
y = 4 + 3 * X + np.random.randn(100, 1)

In [45]:
# perfrom the normal equation calculation
X_b = np.c_[np.ones((100, 1)), X]
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)

In [46]:
# best parameter
theta_best

array([[3.89191348],
       [3.0119644 ]])

In [47]:
# predict with the parameter
X_new = np.array([[0], [2]])
X_new_b = np.c_[np.ones((2,1)), X_new]
y_predict = X_new_b.dot(theta_best)
y_predict

array([[3.89191348],
       [9.91584229]])

In [48]:
# by sklearn and by scipy method is ignored here for simplicity

## Gradient Descent
How to deal with a very larget dataset? (large amount of features or too many training instances to fit in memory)
### Batch Gradient Descent
This is not going to be very fast: it uses every data to calculate derivatives over parameters and move on that direction.

In [53]:
# try to prove we can find the same parameter
eta = 0.1
n_iterations = 1000
m = 100

theta = np.random.randn(2,1) # random initialization: normal distribution of 2 numbers around 1 with std = 1 

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients

In [54]:
theta

array([[3.89191348],
       [3.0119644 ]])

### Stochastic Gradient Descent

In [57]:
# application, details are on the notes: a fast random way of calculating gradient
n_epochs = 50
t0, t1 = 5, 50 # learning schedule hyperparameters

def learning_schedule(t):
    return t0 / (t + t1)

theta = np.random.randn(2,1) # random initialization

for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1]
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients

In [58]:
theta

array([[3.91139806],
       [3.01778664]])

In [60]:
# sklearn do have a SGD model installed
from sklearn.linear_model import SGDRegressor
sgd_reg = SGDRegressor(max_iter=1000, tol=1e-3, penalty=None, eta0=0.1)
sgd_reg.fit(X, y.ravel())

SGDRegressor(eta0=0.1, penalty=None)

In [61]:
sgd_reg.intercept_, sgd_reg.coef_

(array([3.89216208]), array([3.0538402]))